Add content for Layers section
googlefonts/colr-gradients-spec pull request #139
Opened 2020-12-05 06:53 UTC by PeterConstable

Entirely new content.

2020-12-09 04:12 UTC, rsheeter commented on colr-gradients-spec.md
> +The version 1 formats also define layer sets as slices in an array. In this case, however, the array is an array of offsets to paint tables, and is contained in a LayerV1List table. Each referenced p
"The version 1 formats" => "The version 1 format"

2020-12-09 04:22 UTC, rsheeter commented on colr-gradients-spec.md
> +The version 1 formats also define layer sets as slices in an array. In this case, however, the array is an array of offsets to paint tables, and is contained in a LayerV1List table. Each referenced p
This isn't quite right; the list serves a different purpose in V1 and is optional.

COLR v1 defines layer sets as a DAG. Paints _may_ be written into a layer list but do not *have* to be. A COLR v1 font can exist with 0 entries in the LayerV1List.

For example, it would be entirely valid to have a BaseGlyphV1Record with an offset to a PaintGlyph which in turn referenced a PaintSolid and a valid glyph id with no entries in LayerV1List. Pretty sure I even have a unit test to confirm FontTools can output this type of thing.

The reason to write down Paint offsets in the LayerV1List is to allow them to be accessed via PaintColrLayers, thus permitting a compiler to exploit reusable subsequences.

There is a note to this effect buried in https://github.com/googlefonts/colr-gradients-spec#colr-v1-data-structures, LayerV1List table: "Only layers referenced by PaintColrLayers (format 1) records need to be encoded here." BaseGlyphV1Record similarly notes "Offset to Paint, typically a PaintColrLayers."

2020-12-09 04:23 UTC, rsheeter commented on colr-gradients-spec.md
> +**Figure 5.20 PaintColrLayers table used as the root of a color glyph definition.**
Strongly recommend addition of an example where the BaseGlyphV1Record does *not* use PaintColrLayers.

2020-12-09 04:24 UTC, rsheeter commented on colr-gradients-spec.md
> +A PaintColorLayers table can also be nested more deeply within the graph, providing a layer structure to define some component within a larger color glyph definition. The ability to nest a PaintColrL
graphs shall not be acyclic feels like it should be a reference to the section that suggests how this should be accomplished?

2020-12-09 04:25 UTC, rsheeter commented
Loving the examples, just need to tweak the explanation of the LayerV1List. I tried to explain but please kick me in the shins if I failed miserably :)

2020-12-09 04:49 UTC, rsheeter requested changes
Apparently I must comment here. The LayerV1List description needs adjustment.

2020-12-09 05:49 UTC, PeterConstable commented on colr-gradients-spec.md
> +The version 1 formats also define layer sets as slices in an array. In this case, however, the array is an array of offsets to paint tables, and is contained in a LayerV1List table. Each referenced p
The v1 formats in question are the combination of LayerV1List and PaintColrLayers. So, "formats" (plural) was intended.

2020-12-09 05:52 UTC, PeterConstable commented on colr-gradients-spec.md
> +The version 1 formats also define layer sets as slices in an array. In this case, however, the array is an array of offsets to paint tables, and is contained in a LayerV1List table. Each referenced p
Well, I think what is stated there is factually correct in what it says. But perhaps it could be misleading by the comparison with the v0 formats since, in v0, the layers are _the (only) way_ in which a color glyph is defined, whereas in v1, as you point out, the layers are optional. I agree that should be made clear.

2020-12-09 05:53 UTC, PeterConstable commented on colr-gradients-spec.md
> +**Figure 5.20 PaintColrLayers table used as the root of a color glyph definition.**
Agreed.

2020-12-09 22:18 UTC, PeterConstable commented on colr-gradients-spec.md
> +A PaintColorLayers table can also be nested more deeply within the graph, providing a layer structure to define some component within a larger color glyph definition. The ability to nest a PaintColrL
Agreed. Will figure out later where to put that and reference.

2020-12-09 22:27 UTC, PeterConstable commented on colr-gradients-spec.md
> +A PaintColorLayers table can also be nested more deeply within the graph, providing a layer structure to define some component within a larger color glyph definition. The ability to nest a PaintColrL
#156

2020-12-10 06:00 UTC, rsheeter commented on colr-gradients-spec.md
> +Layering of visual elements was introduced above, in the introduction to 5.7.11.1. Both version 0 and version 1 support layers, though in different ways. In version 0, layers are fundamental: they ar
I think this is confusing two things: 1) the existence of a vector of all layers (not strictly required in v1) 2) whether you have layering in the sense of a glyph drawn of z-ordered content (generally speaking true of both [subject to some nuance around PaintComposite]). I suggest replacing with something like:

Layering of visual elements was introduced above, in the introduction to 5.7.11.1. Both version 0 and version 1 support layers. In version 0 there is a single vector of all layers, referenced by all glyphs. In version 1 there is a vector of layers but it's use is optional, required only for sharing of layers between color glyphs using PaintColrLayers.

2020-12-10 06:01 UTC, rsheeter commented on colr-gradients-spec.md
> +For version 0, an array of LayerRecords is created. Each LayerRecord specifies a glyph ID and a CPAL entry (a shape and solid color fill). Each color glyph definition is a slice from that array (that
Given the edit suggested above I think you can delete "A single array is used for defining all color glyphs."

2020-12-10 06:10 UTC, rsheeter commented on colr-gradients-spec.md
> +The version 1 formats also define layer sets as slices in an array. In this case, however, the array is an array of offsets to paint tables, and is contained in a LayerV1List table. Each referenced p
I think this overemphasizes the use of slices of the layer list. You don't *have* to use slices of arrays at all, the core concept is really that it's a graph. I think that means we have to go directly to explaining the graph concept. Spitballing:

The version 1 format defines layer sets as a DAG of paints. The DAG is traversed and each Paint is processed when encountered. For all Paint formats except PaintComposite each subsequent record defines content that overlays the preceding content, just as with version 0. For PaintComposite the mode dictates how the compositing is done. Layers can be shared in three main ways in this model:

1. The Offset to a Paint may point to a Paint that is also referenced by other DAGs
1. PaintColrLayers takes a slice of the LayerV1List, enabling subsets of color glyphs to be shared
1. PaintColrGlyph allows reuse of the complete set of layers making up a color glyph

2020-12-10 06:12 UTC, rsheeter commented on colr-gradients-spec.md
> +Use of layers in a color glyph definition, and of the PaintColrLayers table specifically, is optional. While a PaintColrLayers can be used as the root of a color glyph, this is not required. For exam
You can have layers in the sense of z-ordered content without LayerV1List so instead of "Use of layers" I think you want "Use of the LayerV1List." Also, if you accept some of the suggestions above I think the sentence about it being optional is redundant because we've explained as much earlier.

2020-12-10 06:31 UTC, PeterConstable commented on colr-gradients-spec.md
> +Layering of visual elements was introduced above, in the introduction to 5.7.11.1. Both version 0 and version 1 support layers, though in different ways. In version 0, layers are fundamental: they ar
Well, you're proposed wording is mostly fine and mostly says the same thing, I think. However, for v1, while it is true that the vector of layers is used only in conjuction with PaintColrLayers, it is *not* true that these are used *only* for sharing between color glyphs. If you want a set of layers at all, you will use the LayerV1List + PaintColrLayers because the only other means of layering is via PaintComposite and that only gives two layers at a time.

2020-12-10 06:33 UTC, PeterConstable commented on colr-gradients-spec.md
> +Layering of visual elements was introduced above, in the introduction to 5.7.11.1. Both version 0 and version 1 support layers, though in different ways. In version 0, layers are fundamental: they ar
E.g., figure 5.20: no sharing involved there. Also figure 5.25. Figure 5.30 (later PR) has two PaintColrLayers: one for sharing, and one not.

2020-12-10 06:36 UTC, PeterConstable commented on colr-gradients-spec.md
> +The version 1 formats also define layer sets as slices in an array. In this case, however, the array is an array of offsets to paint tables, and is contained in a LayerV1List table. Each referenced p
First half of that isn't about layers, so should be in this section. Second half is basically the intro already in place for 5.7.11.1.7.

2020-12-10 06:37 UTC, PeterConstable commented on colr-gradients-spec.md
> +Use of layers in a color glyph definition, and of the PaintColrLayers table specifically, is optional. While a PaintColrLayers can be used as the root of a color glyph, this is not required. For exam
How do you create z-ordered content without using LayerV1List? The only other way would be using PaintComposite, and that's only two layers at a time. Nothing else does layering.

2020-12-11 00:28 UTC, PeterConstable commented
Rod & I chatted, and I think we're now on the same page. (Nuances in wording.) I've added a commit that hopefully addresses his concerns.

2020-12-11 05:25 UTC, rsheeter commented on colr-gradients-spec.md
> +example, a simple glyph description need not use any layering, as illustrated in
To me this is still a layer so I dislike the phrasing that *layers* are optional. The optional thing is writing down the offset in the LayerV1List. Perhaps something more like "When using the version 1 format, recording layers in the LayerV1List is optional. For example, a simple glyph can be referenced directly from the BaseGlyphV1Record:"

2020-12-11 05:26 UTC, rsheeter commented on colr-gradients-spec.md
> +* The PaintColrLayers table supports defining a sequence of several layers.
Shouldn't PaintColrGlyph be considered a third way, allows a complete color glyph graph to be reused as part of another color glyphs graph.

2020-12-11 05:29 UTC, rsheeter commented on colr-gradients-spec.md
> +LayerV1List array.
Should we phrase this in specese? - Picturing something like: To be reusable by means of PaintColrLayers Paints shall be recorded in the LayerV1List. Paints not reused by PaintColrLayers should not be recorded in the LayerV1List.

2020-12-11 05:30 UTC, rsheeter approved these changes
Few nits, generally LGTM

2020-12-11 14:45 UTC, PeterConstable commented on colr-gradients-spec.md
> +* The PaintColrLayers table supports defining a sequence of several layers.
PaintColrGlyph doesn't itself increase the layers in the graph.

2020-12-11 14:46 UTC, PeterConstable commented on colr-gradients-spec.md
> +LayerV1List array.
In ISO-ese, a note shall not contain shall. Also, I don't think a font should be invalid if it has a paint offset in the LayerV1List but that is never used by any PaintColrLayers table.

2020-12-11 14:48 UTC, PeterConstable commented on colr-gradients-spec.md
> +* The PaintColrLayers table supports defining a sequence of several layers.
And this section isn't about re-use.

2020-12-11 14:55 UTC, PeterConstable commented on colr-gradients-spec.md
> +example, a simple glyph description need not use any layering, as illustrated in
Sure: there's always at least one layer. I've tweaked wording, including renaming the section "Layering".

2020-12-11 18:46 UTC, drott approved these changes
No objections from my side, but I'd leave it to @rsheeter to finalise the review here, as you and @rsheeter have been discussing this PR in more detail together.

2020-12-11 20:03 UTC, rsheeter commented on colr-gradients-spec.md
> +* The PaintColrLayers table supports defining a sequence of several layers.
> PaintColrGlyph doesn't itself increase the layers in the graph.

I don't quite follow. Think of it this way, it's the same as using PaintColrLayers to reference the complete set of DAG roots that are used by another glyph. 

For example, we have three color glyphs:

1. a BaseGlyph with it's Paint(s) listed in LayerV1List
1. a BaseGlyph that uses PaintColrGlyph to reference the first BaseGlyph
1. a BaseGlyph that uses PaintColrLayers to pull in all the layers of the first BaseGlyph

2 and 3 both pull in all the layers of 1.

2020-12-11 20:05 UTC, rsheeter commented on colr-gradients-spec.md
> +illustrated in figure 5.21:
Curious what @drott and @anthrotype think because this still doesn't feel right to me. I would say the use of LayerV1List is optional but you always have layers. The simple graph only has 1 layer but it's still a layer.

2020-12-11 20:18 UTC, PeterConstable commented on colr-gradients-spec.md
> +* The PaintColrLayers table supports defining a sequence of several layers.
When you reference a DAG using PaintColrGlyph, you get as many layers as there are in the DAG instead of 1 layer. If the DAG has one layer, then you still have only 1 layer. PaintColrGlyph doesn't itself add layers. 

>it's the same as using PaintColrLayers to reference the complete set of DAG roots that are used by another glyph.

This is falling into the same mistake I made earlier, of assuming a DAG starts with a PaintColrLayers. If the DAG does start with PaintColrLayers, then it is PaintColrLayers that adds layers, not the PaintColrGlyph that referenced it. 

>a BaseGlyph with it's Paint(s) listed in LayerV1List

A BaseGlyphV1Record doesn't point into the LayerV1List; it points to a single paint. (You're thinking of the earlier design, before PaintColrLayers was introduced.) So, "Paint(s)" is incorrect. And there's no point in having the paint referenced by the BaseGlyphV1Record be included in the LayerV1List unless that same paint is somewhere else referenced by a PaintColrLayers.

2020-12-11 20:44 UTC, PeterConstable commented on colr-gradients-spec.md
> +illustrated in figure 5.21:
>use of multiple layers

One layer is not multiple layers.

This section is leading with the concepts of each graphic capability, and from there introduce the formats. In this case, the concept is _layering_, i.e. use of multiple layers, and the flow is to start with that concept and then explain how it's achieved. To start out saying "LayerV1List is optional" would change from that pattern by leading with the format.

2020-12-11 23:02 UTC, rsheeter commented on colr-gradients-spec.md
> +* The PaintColrLayers table supports defining a sequence of several layers.
> A BaseGlyphV1Record doesn't point into the LayerV1List; it points to a single paint.

This may be the core of how we're seeing this differently. In "a BaseGlyph with it's Paint(s) listed in LayerV1List" to me "it's Paints" means all the Paints reachable through the graph whose root the BaseGlyph points to. It sounds like you are taking it to mean just the one Paint the BaseGlyph points at (the root), not the entire graph?

2020-12-11 23:37 UTC, rsheeter commented on colr-gradients-spec.md
> +* The PaintColrLayers table supports defining a sequence of several layers.
Resolving pending new content per f2f. I now much better understand what was intended here, ty for explaining.

2020-12-12 03:46 UTC, rsheeter commented on colr-gradients-spec.md
> +illustrated in figure 5.21:
After our f2f chat I better understand where this is coming from, resolving.

2020-12-12 03:47 UTC, rsheeter commented on colr-gradients-spec.md
> +The version 1 formats define a color glyph as a graph of paint tables, and the
s/as a graph of paint/as a directed acyclic graph/; that detail is very important to some readers

2020-12-12 03:52 UTC, rsheeter commented on colr-gradients-spec.md
> +> **_TBD: Add reference to separate section discussing cycles (#156)._**
This should be 5.7.11.1.8 Color glyphs defined as a graph I think looking at master?

2020-12-12 03:54 UTC, rsheeter commented on colr-gradients-spec.md
> +graph is the number of distinct root to leaf paths in the graph.
If layering is conceptually the simple-alpha composition of things in a specific order then I think some PaintComposite modes escape this model, potentially meaning this isn't strictly true. If so I suggest this might need to say the number of visual layers is *at most* the number of leaves?

2020-12-12 03:55 UTC, rsheeter approved these changes
Liking this version much better, ty

2020-12-12 05:23 UTC, PeterConstable commented on colr-gradients-spec.md
> +> **_TBD: Add reference to separate section discussing cycles (#156)._**
I have to add references for that in at least a couple of places, and also update some other numbering, so will take care of that in a later PR.

2020-12-12 05:34 UTC, PeterConstable commented on colr-gradients-spec.md
> +graph is the number of distinct root to leaf paths in the graph.
Well, the same leaf node can potentially be used in multiple layers. So, it's not actually true that the number of visual layers is <= the number of leaf nodes.

But I hadn't considered if some PaintComposite modes complicate the statement. I've opened #165 to consider this further.

2020-12-12 05:37 UTC, merged