Extend content in transformations section
googlefonts/colr-gradients-spec pull request #140
Opened 2020-12-05 07:11 UTC by PeterConstable

2020-12-09 04:28 UTC, rsheeter commented on colr-gradients-spec.md
> +NOTE: Affine transformations have the property that parallel lines remain parallel.
I appreciate the intent but I'm skeptical that in isolation this is helpful; I think we should take the cowards way out and cite something that explains affines.

If we're allowed to cite wikipedia their section of affine is pretty good; https://en.wikipedia.org/wiki/Affine_transformation#/media/File:2D_affine_transformation_matrix.svg gives a nice summary of what you can achieve.

2020-12-09 04:30 UTC, rsheeter commented on colr-gradients-spec.md
> +referenced using a PaintColrGlyph table (see 5.7.11.1.7.3).
Nit: I think it's a stronger statement without the "including a..." bit. All means all, if you start talking about what is included that makes me think something else might not be.

2020-12-09 04:31 UTC, rsheeter commented on colr-gradients-spec.md
> +**Figure 5.21 A rotation transformation rotates the fill content defined by the child sub-graph.**
I didn't find the mirror-Y as obvious as 5.21's rotation. Suggestion: Rotate => Mirror => PaintGlyph => PaintLinearGradiant. Pretty hard to miss that the triangle turned over.

2020-12-09 04:32 UTC, rsheeter commented on colr-gradients-spec.md
> +Whereas the PaintTransformed table supports several types of transforms, the PaintRotate and PaintSkew tables support specific transformations: rotation and skew. The significant difference of these
Anything we could cite for "it is much easier to implement variation of angles when specified directly than when specified using matrix elements."? - if not no worries

2020-12-09 04:43 UTC, rsheeter commented on colr-gradients-spec.md
> +The PaintRotate and PaintSkew tables also provide another advantage for these specific types of transformation, compared to the PaintTransformed table. Rotations or skews implemented with a matrix ar
This isn't right, you can compute a 2x3 that rotates (or skews or whatever) around an arbitrary origin. Any given instance of PaintRotate or Skew has an equivalent 2x3. The primary advantage is making it easy to vary angle. Saving bytes in some situations is a small secondary advantage.

2020-12-09 04:46 UTC, rsheeter commented on colr-gradients-spec.md
> +The PaintRotate and PaintSkew tables also provide another advantage for these specific types of transformation, compared to the PaintTransformed table. Rotations or skews implemented with a matrix ar
Suggest just deleting L1253.

2020-12-09 04:47 UTC, rsheeter requested changes
Approved subject to deletion of the section about PaintTransformed not being able to rotate or skew other than relative to origin. I ... think ... that means I should mark "Request changes."

2020-12-09 05:30 UTC, PeterConstable commented on colr-gradients-spec.md
> +NOTE: Affine transformations have the property that parallel lines remain parallel.
In general, I think there are lots of resources that describe matrix transformations that people can easily find. But finding the meaning of "affine" isn't as easy: for whatever reason, not many resources make a point of explaining that. I learned about matrix transformations in high school, but up through my math undergrad never came across the term "affine". I figured others might be in the same situation, but perhaps I'm accommodating too much to my special case.

2020-12-09 05:34 UTC, PeterConstable commented on colr-gradients-spec.md
> +referenced using a PaintColrGlyph table (see 5.7.11.1.7.3).
The reason I added that is because in the case of PaintColrGlyph there isn't a direct paint -> paint -> paint linkage. It might not be clear to some whether paint -> paint -> **_glyphID_** and glyphID -> paint -> paint comprise one graph or two. That should probably be stated somewhere, but perhaps this isn't the best place.

2020-12-09 05:37 UTC, PeterConstable commented on colr-gradients-spec.md
> +**Figure 5.21 A rotation transformation rotates the fill content defined by the child sub-graph.**
The reason I did it as transform -> glyph -> transform -> gradient was so that there would be two visible elements affected by the first transform but only one visible element affected by the second.

2020-12-09 05:40 UTC, PeterConstable commented on colr-gradients-spec.md
> +Whereas the PaintTransformed table supports several types of transforms, the PaintRotate and PaintSkew tables support specific transformations: rotation and skew. The significant difference of these
For rotation of a given angle, the matrix elements include sin and cos of the angle. It's easy to give a smooth and linear interpolation of the angle, but to do that for matrix elements would either require HOI or else many deltas over "intermediate" ranges. I'll take a stab at giving a rational without going into too much detail.

2020-12-09 05:45 UTC, PeterConstable commented on colr-gradients-spec.md
> +The PaintRotate and PaintSkew tables also provide another advantage for these specific types of transformation, compared to the PaintTransformed table. Rotations or skews implemented with a matrix ar
@rsheeter You can use 2x3 matrices to rotate around an arbitrary point, but not using a single matrix. E.g., if you want to rotate using (say) the point (2, 3) as the center or rotation, using 2x3 matrices you would need to do this in three steps: translate (-2, -3), then rotate, then translate (2, 3). The rotation needs to be wrapped by distinct translations. The PaintRotate table allows this to be stated directly in a single table.

2020-12-09 13:22 UTC, drott reviewed
Could you add some kind of source images for the illustrations, .eps, .pdf, .ai or similar? 

For Figure 5.22, may I suggest to add in the PaintTransform block to explain by how many degrees this transform rotates?

2020-12-09 14:32 UTC, drott commented on colr-gradients-spec.md
> +The PaintRotate and PaintSkew tables also provide another advantage for these specific types of transformation, compared to the PaintTransformed table. Rotations or skews implemented with a matrix ar
The matrices A (translate), B (rotate), C (translate back) in your example can be combined into one equivalent affine combining the three, resulting in the same transform.

2020-12-09 15:58 UTC, PeterConstable commented on colr-gradients-spec.md
> +The PaintRotate and PaintSkew tables also provide another advantage for these specific types of transformation, compared to the PaintTransformed table. Rotations or skews implemented with a matrix ar
OK, convinced myself of that by extending the 2x3 into 3x3 and composing those. (You can't directly compose 2x3s.)

2020-12-09 17:16 UTC, rsheeter commented on colr-gradients-spec.md
> +Whereas the PaintTransformed table supports several types of transforms, the PaintRotate and PaintSkew tables support specific transformations: rotation and skew. The significant difference of these
Something terse to that effect strikes me as worth including, it's one of the least obvious things in here imho.

...just noticed the `<span>`; let's try not to mix html in if at all possible

2020-12-09 18:58 UTC, PeterConstable commented on colr-gradients-spec.md
> +Whereas the PaintTransformed table supports several types of transforms, the PaintRotate and PaintSkew tables support specific transformations: rotation and skew. The significant difference of these
The <span> will be removed once I know what the clause ref will be.

2020-12-09 19:04 UTC, rsheeter commented on colr-gradients-spec.md
> +NOTE: Affine transformations have the property that parallel lines remain parallel.
I think the text you have about this enabling rotate, skew, etc will be helpful to someone who hasn't seen an affine transform. I suggest either delete the note or change it to be a reference: "See blah for more about affine transformations"

2020-12-09 19:14 UTC, rsheeter commented on colr-gradients-spec.md
> +NOTE: Affine transformations have the property that parallel lines remain parallel.
Maybe cite https://www.w3.org/TR/css-transforms-1/#mathematical-description and note how our fields map to the abcdef shown there

2020-12-09 19:15 UTC, rsheeter commented on colr-gradients-spec.md
> +**Figure 5.21 A rotation transformation rotates the fill content defined by the child sub-graph.**
Don't *have* to change anything, I just found that unlike the other examples where you can see at a glance what's happening for this one I had to stop and look at it to spot what it was telling me

2020-12-09 19:16 UTC, rsheeter commented
If Dominik change is made and L1253 is deleted IMHO this could be merged

2020-12-09 19:56 UTC, PeterConstable commented on colr-gradients-spec.md
> +NOTE: Affine transformations have the property that parallel lines remain parallel.
We explain our matrix elements clearly, and cross-ref to CSS might only create confusion. I'll drop the note.

2020-12-09 20:12 UTC, PeterConstable commented on colr-gradients-spec.md
> +**Figure 5.21 A rotation transformation rotates the fill content defined by the child sub-graph.**
Added a bit of text to call out the details.

2020-12-09 20:12 UTC, PeterConstable commented on colr-gradients-spec.md
> +referenced using a PaintColrGlyph table (see 5.7.11.1.7.3).
Removed here. Will consider mention elsewhere (cf. #151)

2020-12-09 21:47 UTC, rsheeter approved these changes

2020-12-09 21:47 UTC, merged

2020-12-10 10:15 UTC, drott commented
> Could you add some kind of source images for the illustrations, .eps, .pdf, .ai or similar?

@PeterConstable - what about vector source images for `images/colr_transform_glyph_gradient.png` and `images/colr_transform_glyph_transform_gradient.png` - would it be possible to add those?

2020-12-10 14:09 UTC, PeterConstable commented
>@PeterConstable - what about vector source images for images/colr_transform_glyph_gradient.png and images/colr_transform_glyph_transform_gradient.png - would it be possible to add those?

@drott Sorry, meant to reply: I assemble all of these images in a single Powerpoint file, which is binary. I'll add that after the last PR for Graphic components is merged.