Update PaintTranslate/Rotate/Skew
googlefonts/colr-gradients-spec pull request #177
Opened 2020-12-17 03:21 UTC by PeterConstable

In the NOTEs for PaintRotate/PaintSkew, I dropped the mention of angles being more amenable to smooth rotation. That's covered in a note in 5.7.11.1.5 Transformations, and that note has more explanation as to why that assertion is true.

2020-12-20 04:00 UTC, rsheeter commented on colr-gradients-spec.md
> +origin of the source, (0,0), is aligned to the destination origin.
It would be nice to only say this once rather than in every Paint that produces an affine. Or, as noted in the PaintTransformed PR just don't say it because for the most part this is reasoned about as just bouncing points around.

2020-12-20 04:00 UTC, rsheeter commented on colr-gradients-spec.md
> +NOTE: Translation can also be represented using the PaintTransformed table. The
Suggest noting what the equivalent PaintTransformed would be.

2020-12-20 04:02 UTC, rsheeter commented on colr-gradients-spec.md
> +degrees, rather than as changes to basis vectors.
I think the point about allowing smooth rotation on an axis was important, suggest not removing.

2020-12-20 04:05 UTC, rsheeter requested changes
Why remove mention of the value to variable fonts? - thats important for Rotate and Skew

2020-12-20 22:15 UTC, PeterConstable commented on colr-gradients-spec.md
> +origin of the source, (0,0), is aligned to the destination origin.
I want to say it at once since it might not be obvious to some readers that don't have experience in 2D graphic implementations.

2020-12-20 22:44 UTC, PeterConstable commented on colr-gradients-spec.md
> +NOTE: Translation can also be represented using the PaintTransformed table. The
I'll do it for rotate/skew assuming rotation about the origin. (For other centers, it's overly complicated.)

2020-12-20 23:08 UTC, PeterConstable commented on colr-gradients-spec.md
> +degrees, rather than as changes to basis vectors.
It was stated earlier in 5.7.11.1.5, but by spelling out equivalent matrix values it fits OK to do here as well.

2020-12-21 20:06 UTC, rsheeter commented on colr-gradients-spec.md
> +* _dx_ = _dy_ = 0
Looking at https://en.wikipedia.org/wiki/Affine_transformation#/media/File:2D_affine_transformation_matrix.svg I think perhaps the - is on the x part of y basis (xy) where it should be on the y part of x basis (yx)?

* _yx_ = - sin(&theta;)
* _xy_ = sin(&theta;)

2020-12-21 20:09 UTC, PeterConstable commented on colr-gradients-spec.md
> +* _dx_ = _dy_ = 0
Check the direction of the rotation: our format uses counter-clockwise degrees. That figure is using clockwise rotation. Sign of sine is opposite.

2020-12-21 20:10 UTC, rsheeter approved these changes

2020-12-21 20:11 UTC, rsheeter commented on colr-gradients-spec.md
> +* _dx_ = _dy_ = 0
Ah you are right, forgot we said counter-clockwise when comparing.

2020-12-21 20:11 UTC, merged