Add CPAL edits re sRGB 'gamma' and interpolation
googlefonts/colr-gradients-spec pull request #214
Opened 2021-01-14 04:10 UTC by PeterConstable

There's a little bit of intro-to-concepts content since readers of the OFF/OT spec come from a wide variety of backgrounds, and jumping straight to a statement like "compute using linear RGB" won't mean anything for many.

Linear RGB for blending isn't added here since that's will fit better in the COLR section on compositing, so will come separately. But a "for more info" pointer to the CPAL section can be included.

2021-01-14 13:00 UTC, drott reviewed
Thanks, Peter, for drafting this chapter, a few comments below. Disclaimer: I am certainly not an expert on color and related computations, so I might confuse things as well here.

2021-01-14 13:00 UTC, drott commented on OFF_AMD2_WD.md
> +expressed using a linear-light-energy scale. For sRGB, however, standard
> linear-light-energy scale
is introduced here without much explanation. Perhaps we can explain a bit what it is: i.e. evenly spaced segmentation of the color channel contribution to the color value, and about how a linear encoding would lead to lack of resolution in the darker parts of the color channel due to how visual perception works?

2021-01-14 13:00 UTC, drott commented on OFF_AMD2_WD.md
> +using floating values. Also, when rendered results are to be presented on a
I suggest to drop the recommendation to use float values, this seems too specific. As discussed in the meeting yesterday, perhaps we can say instead that it should be done with higher precision than with the 8bit values coming from the encoding?

2021-01-14 13:00 UTC, drott commented on OFF_AMD2_WD.md
> +can be minimized by taking full advantage of the color bit depth supported by
```suggestion
imaging device with known characteristics, visual banding effects in a gradient
can be minimized by taking full advantage of the color bit depth supported by
```

2021-01-14 13:00 UTC, drott commented on OFF_AMD2_WD.md
> +While color values are specified as 8-bit integers, the interpolation
Move this paragraph to a note?

2021-01-14 22:48 UTC, PeterConstable commented on OFF_AMD2_WD.md
> +expressed using a linear-light-energy scale. For sRGB, however, standard
This stuff is actually deeply complicated when you get into the details. 

(The linear RGB values in an image are representations captured illuminance and expected display luminance. The latter is related to radiance by incorporation of the standard observer spectral responsiveness in spectral integration, and is measured in watts per square meter per steradian... and on and on... And the background for non-linear transfer functions also gets into the response behaviour in electron guns and phosphors in CRTs, as well as factors related to expecting viewing environments... and on and on...)

So a bit of thinking is needed to figure what can be said that's accurate, understandable, and useful.

The distribution of quantized distinctions and the nature of human visual response (more sensitive to differences at low luminance levels than at high levels) is probably useful. So, I'll work on what to say that's also accurate and understandable.

2021-01-15 02:20 UTC, PeterConstable commented
I've added the text on blending using linear color values (#211).

2021-01-18 17:03 UTC, PeterConstable commented on OFF_AMD2_WD.md
> +using floating values. Also, when rendered results are to be presented on a
Yeah, I almost didn't include that.

2021-01-18 18:37 UTC, drott commented on OFF_AMD2_WD.md
> +Therefore, no minimum level of precision is specified as a requirement.
Nit from a non-native English speaker, so this might be just a personal impression: The trailing ", however." irritates my reading flow a bit when the next word is "Therefore...". I suggest to move "however" to the beginning of the sentence or after _may_.

2021-01-18 18:39 UTC, drott reviewed
This looks good to me but it'd be great to have @svgeesus 's feedback on this PR. Also, @bungeman , do you have any further comments?

2021-01-19 13:26 UTC, svgeesus commented
> This looks good to me but it'd be great to have @svgeesus 's feedback on this PR

Yes I will try to review today

2021-01-21 16:57 UTC, PeterConstable commented
@svgeesus Any chance you can review this soon?

2021-01-29 01:27 UTC, svgeesus requested changes
Overall very good and requiring minimal changes.

The un-premultiplication step to get back actual colors was the major missing portion.

2021-01-29 01:27 UTC, svgeesus commented on OFF_AMD2_WD.md
> +transfer function to derive linear RGB values. For more information regarding
Linear is being used in two senses here - linear interpolation, and linear-light. I suggest therefore changing this from linear RGB""to "linear-light sRGB"

2021-01-29 01:27 UTC, svgeesus commented on OFF_AMD2_WD.md
> +the non-linear sRGB scale (the default), or using a linear scale by applying the
that is the default, sadly, but not because it is better necessarily. It was also faster (in 1999).

(not a change request, just an observation)

2021-01-29 01:27 UTC, svgeesus commented on OFF_AMD2_WD.md
> +using linear values after applying the inverse sRGB transfer function.
Again, ""linear-light"would be clearer here

2021-01-29 01:27 UTC, svgeesus commented on OFF_AMD2_WD.md
> +interpolation using these pre-multiplied, linear R, G and B values.
This is correct as far as it goes, but misses a step. Add:

Once interpolation of the premultiplied red, green and blue values, and the alpha, is complete the results are then un-premultiplied by dividing each of the premultiplied red, green and blue values by the value of alpha.

2021-02-01 23:29 UTC, PeterConstable commented on OFF_AMD2_WD.md
> +interpolation using these pre-multiplied, linear R, G and B values.
@svgeesus: Part of your proposed addition isn't clear to me: "dividing... by the value of alpha". Which alpha value? 

I'm guessing that, for each stop offset of a gradient, the interpolated, premultiplied RGB values are divided by the interpolated alpha? I've updated the text assuming that to be the case. Please confirm.

2021-02-02 12:58 UTC, svgeesus commented on OFF_AMD2_WD.md
> +interpolation using these pre-multiplied, linear R, G and B values.
Yes, the interpolated, premultiplied color value is divided by the interpolated alpha value, to get back actual colors.

2021-02-02 13:01 UTC, svgeesus approved these changes
One minor wording suggestion but otherwise this is great.

2021-02-02 13:01 UTC, svgeesus commented on OFF_AMD2_WD.md
> +using linear-light values after applying the inverse sRGB transfer function.
Actually that is now slightly ambiguous. Perhaps

"must be computed using linear values after (i.e., applying the inverse sRGB transfer function)."

2021-02-02 13:01 UTC, svgeesus commented on OFF_AMD2_WD.md
> +un-premultiplied by dividing each interpolated value by the corresponding
yes

2021-02-02 17:34 UTC, merged