Give COLR an explicit bbox to call it's own
googlefonts/colr-gradients-spec pull request #321
Opened 2021-07-14 05:10 UTC by rsheeter

Strawman for a fix for #251

2021-07-14 05:36 UTC, rsheeter commented
Another interesting benefit: bbox sharing Just Works, for things with repetitive bboxes (emoji, icons) that's a win.

2021-07-14 07:28 UTC, justvanrossum commented on OFF_AMD2_WD.md
> +| UFWORD | h | height of bounding box. For variation, use varIndexBase + 3. |
Any particular reason to use width/height instead of max_x/max_y? Intuitively I think absolute coordinates are easier to deal with in the context of variations.

2021-07-14 15:54 UTC, PeterConstable commented on OFF_AMD2_WD.md
> +| UFWORD | h | height of bounding box. For variation, use varIndexBase + 3. |
I agree: I'd use xMin, yMin, xMax, yMax to match what is done in the 'glyf' and 'head' tables.

2021-07-14 15:55 UTC, PeterConstable commented on OFF_AMD2_WD.md
> +| UFWORD | x | x-coord of bounding box. For variation, use varIndexBase + 0. |
These need to be FWORD, not UFWORD.

2021-07-14 16:59 UTC, PeterConstable requested changes

2021-07-14 16:59 UTC, PeterConstable commented on OFF_AMD2_WD.md
> +| Offset32 | bboxOffset | Offset to a VarBBox table. |
I'd state explicitly that bboxOffset can be NULL, in which case the bbox data is taken from the base glyph data. I don't see any downside of allowing that for cases in which that would be adequate, and it can save 12 bytes per colour glyph.

2021-07-14 16:59 UTC, PeterConstable commented on colr-gradients-spec.md
> +  UFWORD                 x; // VarIdx varIndexBase + 0.
Type should be FWORD. Change members to xMin, yMin, xMax, yMax.

2021-07-14 18:34 UTC, rsheeter commented on OFF_AMD2_WD.md
> +| UFWORD | x | x-coord of bounding box. For variation, use varIndexBase + 0. |
Good catch, fixing

2021-07-14 18:36 UTC, rsheeter commented on OFF_AMD2_WD.md
> +| UFWORD | h | height of bounding box. For variation, use varIndexBase + 3. |
Apparently somewhere along the line x,y,w,h stuck in my head as the definition of box :) Agreed it's best to match existing practice.

2021-07-14 18:45 UTC, rsheeter commented on OFF_AMD2_WD.md
> +| Offset32 | bboxOffset | Offset to a VarBBox table. |
I waffle a bit on that one. Thinking "aloud", two reasons to potentially not do that:

1. Simplicity. Bbox is trivially accessible for both glyf and cff with COLR.
1. Discussion on #251 where a pretty expert group of users expressed concern with use of base glyph

2021-07-14 18:45 UTC, rsheeter commented on OFF_AMD2_WD.md
> +| UFWORD | h | height of bounding box. For variation, use varIndexBase + 3. |
Done

2021-07-14 18:45 UTC, rsheeter commented on OFF_AMD2_WD.md
> +| UFWORD | x | x-coord of bounding box. For variation, use varIndexBase + 0. |
Done

2021-07-14 18:45 UTC, rsheeter commented on colr-gradients-spec.md
> +  UFWORD                 x; // VarIdx varIndexBase + 0.
Done

2021-07-14 18:48 UTC, rsheeter commented on OFF_AMD2_WD.md
> +| Offset32 | bboxOffset | Offset to a VarBBox table. |
Would it only be true for `glyf` that bbox as described in https://docs.microsoft.com/en-us/typography/opentype/spec/glyf is sufficient or is that true of CFF as well?

2021-07-14 18:50 UTC, PeterConstable commented on OFF_AMD2_WD.md
> +| Offset32 | bboxOffset | Offset to a VarBBox table. |
>Simplicity. Bbox is trivially accessible for both glyf and cff with COLR.

Not clear to me what you're saying and why it argues against optionality.

> Discussion on [issue 251...] where a pretty expert group of users expressed concern with use of base glyph

@raphlinus brought up something that I think is a non-issue. I don't There are working implementations of COLR v1 now that have successfully used bbox info from 'glyf'. Those work without issue.

2021-07-14 19:09 UTC, PeterConstable commented on OFF_AMD2_WD.md
> +| Offset32 | bboxOffset | Offset to a VarBBox table. |
>Would it only be true for glyf that bbox as described in [OT 'glyf' spec] is sufficient or is that true of CFF as well?

The concept of the bounding box described in the 'glyf' chapter — derived from point coordinate data for on- or off-curve points — would apply equally to CFF(2) as well as to 'glyf'. However, whereas in the 'glyf' table the glyph entries include the bbox values (xMin, etc.), I don't think there's an equivalent in CFF(2) entries. So, a bbox would have to be computed by processing the charstring data.

We could say that a bbox table _should_ (or _must_ / _shall_) be used for fonts that use CFF(2) for base glyphs.

2021-07-14 19:51 UTC, PeterConstable commented on colr-gradients-spec.md
> +struct VarBBox {
Since the same struct will be used for both variable and non-variable cases, is "Var" needed in the name? (We add "Var" in other structs when we're distinguishing from a corresponding non-variable struct.)

2021-07-14 20:57 UTC, rsheeter commented on colr-gradients-spec.md
> +struct VarBBox {
I was going for consistency in that Var* would be a variable thing. Don't really have strong feelings about it.

2021-07-14 21:06 UTC, rsheeter commented on OFF_AMD2_WD.md
> +| Offset32 | bboxOffset | Offset to a VarBBox table. |
I prefer not to have a case where you process the CFF or glyf glyph to get the box. To achieve that I believe I need  it for CFF, and I need it for a variable glyf, and I need it for a glyf with an alternate representation, so we'd be making it optional solely when  there is a glyf table and the bbox desired exists in glyf. And it should be fairly efficient given it's sharable. That leaves me thinking having it mandatory makes sense. WDYT?

2021-07-14 21:09 UTC, rsheeter commented on colr-gradients-spec.md
> +struct VarBBox {
Per IM discussion, leaving VarBBox

2021-07-14 21:19 UTC, PeterConstable approved these changes

2021-07-14 21:24 UTC, PeterConstable commented
@googlebot I consent

2021-07-14 21:26 UTC, rsheeter commented on OFF_AMD2_WD.md
> +| Offset32 | bboxOffset | Offset to a VarBBox table. |
Resolving per IM and PR approval w/bbox mandatory

2021-07-14 21:26 UTC, merged

2021-07-15 14:08 UTC, anthrotype commented
> The same structure is used in both variable and non-variable fonts.

why not having distinct BBox and VarBBox structs and save the unused 4 bytes?

2021-07-15 15:08 UTC, PeterConstable commented
How would you determine which structure to read? Have a VarBaseGlyphPaintRecord (and whatever else that might entail)? Have the format for the (Var)BBox table conditioned by whether COLR.itemVariationStoreOffset == NULL?

2021-07-15 15:30 UTC, anthrotype commented
ah good point, I had not thought about that. I'm not sure actually.
Checking if VarStore != NULL to determine whether to parse static BBox vs VarBBox would mean that if any color glyph has some COLR variations (and thus has a non-null VarStore), then all the color glyphs (even those that actually do not vary) will use VarBBox.
Perhaps adding a uint8 format to BaseGlyphPaintRecord that says whether it can vary or not (which selects the appropriate BBox or VarBBox), but then we'd spend 1 byte to save 4 so the net effect would be 3 bytes saved overall for static-only fonts, and +1 byte for each color glyphs that can vary in a color VF.
But I'm not sure if it's actually worth it.

2021-07-15 17:01 UTC, rsheeter commented
After sanity checking we actually get quite a lot of unique bboxes (text fonts just for comparison, they aren't COLR):

```
twemoji-glyf_colr_1.ttf 10622 unique bboxes
noto-glyf_colr_1.ttf 39370 unique bboxes
Roboto[wdth,wght].ttf 1058 unique bboxes
Arimo[wght].ttf 2503 unique bboxes
```

Maybe worthwhile indeed.

2021-07-16 19:52 UTC, behdad commented
I think merging this was premature.

What happens when the paint tries to paint outside the bbox? I don't see that specified. And if not specified, we are bound to see fonts that have bogus bounding box info.

2021-07-16 19:55 UTC, rsheeter commented
I don't think this changes that concern? - we already said you should be
able to use a provided bbox, this merely changes where that lives

On Fri, Jul 16, 2021 at 12:53 PM Behdad Esfahbod ***@***.***>
wrote:

> I think merging this was premature.
>
> What happens when the paint tries to paint outside the bbox? I don't see
> that specified. And if not specified, we are bound to see fonts that have
> bogus bounding box info.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/googlefonts/colr-gradients-spec/pull/321#issuecomment-881681694>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABRKXAC32LBOO6PHLDP3Q7TTYCEZ7ANCNFSM5AKV5EGA>
> .
>

2021-07-16 20:01 UTC, behdad commented
> I don't think this changes that concern? - we already said you should be able to use a provided bbox, this merely changes where that lives

What bothers me most is that this is not even optional. The byte cost cannot be avoided by an implementation that wouldn't need it.

What should have been done instead was to address Ben's concerns by specing out how to calculate bounding box on the fly. This is a very well-known problem. You simply have to run the paint graph / draw twice: first to calculate the bounds so you can allocate, second to do the drawing.

What has happened here is typical of when implementors and spec writers are too close. Things go into the spec without being fully justified. Variations, indeed, as have been pointed out multiple times, make it *impossible* to even specify bounding boxes.

Even before PaintRotate, the *tight* bounding box of an OpenType 1.8 Variable Font was *not* expressible as a variable value using the same variable model.  It *was* possible to specify a non-tight box easily-enough though.

With PaintRotate, even that is not doable. So, to address a concern about rasterization time, one that is well-understood and easily solvable, you have now encoded requirements for the compiler, that we have no idea how to implement.

Indeed, it was fine closing https://github.com/googlefonts/colr-gradients-spec/issues/289 because an implementation did NOT have to use the encoded bbox. But now we are explicitly forcing compilers to compute that, something we don't have a known way to do, short of walking every glyph outline point and calculating it's max bounds under the PaintGraph.

In short, you've replaced a tractable problem with an intractable one.

2021-07-16 20:05 UTC, behdad commented
The same thing happened at OTVar1.8 time: MS insisted that bbox variations must be encoded explicitly and forced it through in HVAR/VVAR tables despite objections; only later it was realized that those cannot be encoded given the existing variation model. It's still hanging over our head. Why is that issue being ignored, even in the face of the more problematic PaintRotate?